// Exporting the CLINICIAN_MEDICATION_MISTAKE_DICT as a JavaScript object
const CLINICIAN_MEDICATION_MISTAKE_DICT = {
    "atopex": "Adipex",
    "admalog": "Admelog",
    "avara": "Advair",
    "adzenis": "Adzenys",
    "amavig": "Aimovig",
    "amivig": "Aimovig",
    "amovig": "Aimovig",
    "amavac": "Aimovig",
    "aimavig": "Aimovig",
    "ajovi": "Ajovy",
    "adjuvi": "Ajovy",
    "aldera": "Aldara",
    "malagra": "Allegra",
    "avesco": "Alvesco",
    "amgevita": "Amjevita",
    "amgivita": "Amjevita",
    "anoro elipta": "Anoro Ellipta",
    "astralin": "Astelin",
    "astalyn": "Astelin",
    "atomet": "Atrovent",
    "agestin": "Aygestin",
    "azzo": "Azo",
    "balsamra": "Belsomra",
    "velzuta van": "Belzutifan",
    "victarvy": "Biktarvy",
    "victarbi": "Biktarvy",
    "brena": "Breyna",
    "bisperone": "Busiprone",
    "boost bar": "Buspar",
    "pistolic": "Bystolic",
    "c 1": "C1",
    "c 2": "C2",
    "c 3": "C3",
    "c 4": "C4",
    "c 5": "C5",
    "c 6": "C6",
    "c 7": "C7",
    "c1": "C1",
    "c2": "C2",
    "c3": "C3",
    "c4": "C4",
    "c5": "C5",
    "c6": "C6",
    "c7": "C7",
    "cabinuva": "Cabenuva",
    "sepakol": "Cepacol",
    "sequa": "Cequa",
    "cetracil": "Citrucel",
    "coligard": "Cologuard",
    "cosab": "Cosopt",
    "cozar": "Cozaar",
    "chromalin": "Cromolyn",
    "symbalta": "Cymbalta",
    "deep flap": "DIEP flap",
    "delsim": "Delsym",
    "demoralized bone matrix": "demineralized bone matrix",
    "dyscovi": "Descovy",
    "discal shavers": "disc shavers",
    "dorvato": "Dovato",
    "ducalax": "Dulcolax",
    "duracef": "Duricef",
    "imgality": "Emgality",
    "infortimab": "Enfortumab",
    "invarsus": "Envarsus",
    "invarsys": "Envarsus",
    "epidioloex": "Epidiolex",
    "equaid": "Equate",
    "aviccio": "Evekeo",
    "avequio": "Evekeo",
    "evolut procor valve": "Evolut Pro CoreValve",
    "x-forge": "ExForge",
    "ilea": "Eylea",
    "izuvis": "Eysuvis",
    "carbrixa": "Farxiga",
    "varziga": "Farxiga",
    "fioricept": "Fioricet",
    "vermagon": "Firmagon",
    "flonates": "Flonase",
    "floence": "Flonase",
    "fluoro copy": "fluoroscopy",
    "fulfironox": "Folfirinox",
    "folfaxus": "Folfox",
    "folphiila": "Fulphila",
    "folphila": "Fulphila",
    "gainsland's": "Gaenslen's",
    "gasex": "Gas-X",
    "hemocytorin": "Hemosiderin",
    "hykiden": "Hycodan",
    "hizar": "Hyzaar",
    "icichan": "IcyHot",
    "icu": "ICU",
    "lumia": "Ilumya",
    "ambresia": "Inbrija",
    "incredibrace": "Incrediwear",
    "enlyta": "Inlyta",
    "izabloom": "Isibloom",
    "jacofi": "Jakafi",
    "giardiance": "Jardiance",
    "gel mito": "Jelmyto",
    "junal": "Junel",
    "capve": "Kapvay",
    "capfe": "Kapvay",
    "cardiomobile": "KardiaMobile",
    "kazimta": "Kesimpta",
    "qsympta": "Kesimpta",
    "claralight": "Klaralyte",
    "kylena": "Kyleena",
    "kylene": "Kyleena",
    "l 1": "L1",
    "l 2": "L2",
    "l 3": "L3",
    "l 4": "L4",
    "l 5": "L5",
    "l1": "L1",
    "l2": "L2",
    "l3": "L3",
    "l4": "L4",
    "l5": "L5",
    "l1 s1": "L1-S1",
    "l 1 s 1": "L1-S1",
    "l1 s2": "L1-S2",
    "l 1 s 2": "L1-S2",
    "l1 s3": "L1-S3",
    "l 1 s 3": "L1-S3",
    "l1 s4": "L1-S4",
    "l 1 s 4": "L1-S4",
    "l1 s5": "L1-S5",
    "l2 s1": "L2-S1",
    "l 2 s 1": "L2-S1",
    "l2 s2": "L2-S2",
    "l 2 s 2": "L2-S2",
    "l2 s3": "L2-S3",
    "l 2 s 3": "L2-S3",
    "l2 s4": "L2-S4",
    "l 2 s 4": "L2-S4",
    "l2 s5": "L2-S5",
    "l 2 s 5": "L2-S5",
    "l3 s1": "L3-S1",
    "l 3 s 1": "L3-S1",
    "l3 s2": "L3-S2",
    "l 3 s 2": "L3-S2",
    "l3 s3": "L3-S3",
    "l 3 s 3": "L3-S3",
    "l3 s4": "L3-S4",
    "l 3 s 4": "L3-S4",
    "l3 s5": "L3-S5",
    "l 3 s 5": "L3-S5",
    "l4 s1": "L4-S1",
    "l 4 s 1": "L4-S1",
    "l4 s2": "L4-S2",
    "l 4 s 2": "L4-S2",
    "l4 s3": "L4-S3",
    "l 4 s 3": "L4-S3",
    "l4 s4": "L4-S4",
    "l 4 s 4": "L4-S4",
    "l4 s5": "L4-S5",
    "l 4 s 5": "L4-S5",
    "l5 s1": "L5-S1",
    "l 5 s 1": "L5-S1",
    "l5 s2": "L5-S2",
    "l 5 s 2": "L5-S2",
    "l5 s3": "L5-S3",
    "l 5 s 3": "L5-S3",
    "l5 s4": "L5-S4",
    "l 5 s 4": "L5-S4",
    "l5 s5": "L5-S5",
    "l 5 s 5": "L5-S5",
    "lockman's test": "Lachman's test",
    "zinitidine": "Lasmiditan",
    "levobalbuterol": "Levalbuterol",
    "levofet": "Levophed",
    "lefremini": "Li Fraumeni",
    "loroastrin": "Loestrin",
    "lurina": "Loryna",
    "lotrizone": "Lotrisone",
    "malampati": "Mallampati",
    "malpighi": "Mallampati IV",
    "maxotral": "Maxitrol",
    "clavuloplasty": "McCall culdoplasty",
    "muralax": "Miralax",
    "marina iud": "Mirena IUD",
    "malnupiravir": "Molnupiravir",
    "manjaro": "Mounjaro",
    "menjara": "Mounjaro",
    "moongiro": "Mounjaro",
    "moonjaro": "Mounjaro",
    "mujaro": "Mounjaro",
    "munjaro": "Mounjaro",
    "munjara": "Mounjaro",
    "menjaro": "Mounjaro",
    "monjano": "Mounjaro",
    "monjuro": "Mounjaro",
    "mongero": "Mounjaro",
    "monjera": "Mounjaro",
    "amounjaro": "Mounjaro",
    "mundaro": "Mounjaro",
    "amunjaro": "Mounjaro",
    "bonjarno": "Mounjaro",
    "majoro": "Mounjaro",
    "mitophenolate": "Mycophenolate",
    "mervitriq": "Myrbetriq",
    "nealmed": "NeilMed",
    "nerevia": "Nerivio",
    "nupro patch": "Neupro patch",
    "novolumab": "Nivolumab",
    "novolyumab": "Nivolumab",
    "nevolumab": "Nivolumab",
    "northendrone": "Northindrone",
    "notchoconnect": "Northshore Connect",
    "nubeca": "Nubeqa",
    "nertec": "Nurtec",
    "nerteq": "Nurtec",
    "nertex": "Nurtec",
    "nertrac": "Nurtec",
    "neurotec": "Nurtec",
    "neurotech": "Nurtec",
    "norcheck": "Nurtec",
    "nortrek": "Nurtec",
    "opil": "Opill",
    "orlyza": "Orilissa",
    "orthotricycline": "Ortho Tri-Cyclen",
    "ezempic": "Ozempic",
    "ozembic": "Ozempic",
    "osempic": "Ozempic",
    "otezia": "Ozempic",
    "ozembeq": "Ozempic",
    "ozymbic": "Ozempic",
    "ozympic": "Ozempic",
    "ozempia": "Ozempic",
    "osampic": "Ozempic",
    "zempic": "Ozempic",
    "palmer point": "Palmer's Point",
    "perry romberg syndrome": "Parry-Romberg syndrome",
    "patinase": "Patanase",
    "paxilobin": "Paxlovid",
    "pediashore": "Pediasure",
    "pepsid": "Pepcid",
    "pepitamin": "Peptamen",
    "peptamine": "Peptamen",
    "prajita": "Perjeta",
    "pics disease": "Pick's Disease",
    "plaquenol": "Plaquenil",
    "polytrin": "Polytrim",
    "paralysic": "Prilosec",
    "quelbry": "Qelbree",
    "quiloment": "Quillivant",
    "q-lypta": "Qulipta",
    "qlipda": "Qulipta",
    "q lipta": "Qulipta",
    "qlipto": "Qulipta",
    "qlypto": "Qulipta",
    "culepta": "Qulipta",
    "qlipta": "Qulipta",
    "qlipt": "Qulipta",
    "onculipta": "Qulipta",
    "quivivic": "Quviviq",
    "arthrope": "R-CHOP",
    "renaud's phenomenon": "Raynaud's phenomenon",
    "rectoseal": "Rectocele",
    "real pex": "Relpax",
    "ropex": "Relpax",
    "replenz": "Replens",
    "revoshio": "Revatio",
    "rigzolti": "Rexulti",
    "resiroc": "Rezurock",
    "rain air": "RhinAer",
    "rebelsis": "Rybelsus",
    "ribelsis": "Rybelsus",
    "rebeltus": "Rybelsus",
    "ribelsus": "Rybelsus",
    "s 1": "S1",
    "s 2": "S2",
    "s 3": "S3",
    "s 4": "S4",
    "s 5": "S5",
    "s1": "S1",
    "s2": "S2",
    "s3": "S3",
    "s4": "S4",
    "s5": "S5",
    "celsin blue": "Selsun Blue",
    "simaglutide": "Semaglutide",
    "semgly": "Semglee",
    "sena s": "Senna-S",
    "sena-s": "Senna-S",
    "senacot s": "Senokot-S",
    "senacot-s": "Senokot-S",
    "celexan": "Silexan",
    "xymethicone": "Simethicone",
    "slomag": "SlowMag",
    "slend": "Slynd",
    "sprintek": "Sprintec",
    "sperling's": "Spurling's",
    "stiglatro": "Steglatro",
    "stialto": "Stiolto",
    "sinsbeak": "Synvisc",
    "cysteine": "Systane",
    "sustane": "Systane",
    "t 1": "T1",
    "t 2": "T2",
    "t 3": "T3",
    "t 4": "T4",
    "t 5": "T5",
    "t 6": "T6",
    "t 7": "T7",
    "t 8": "T8",
    "t 9": "T9",
    "t 10": "T10",
    "t 11": "T11",
    "t 12": "T12",
    "t1": "T1",
    "t2": "T2",
    "t3": "T3",
    "t4": "T4",
    "t5": "T5",
    "t6": "T6",
    "t7": "T7",
    "t8": "T8",
    "t9": "T9",
    "t10": "T10",
    "t11": "T11",
    "t12": "T12",
    "tessalon perls": "Tessalon Perles",
    "tessalon pearls": "Tessalon Perles",
    "ticosin": "Tikosyn",
    "tecosin": "Tikosyn",
    "ticasin": "Tikosyn",
    "tecasin": "Tikosyn",
    "tenelle's": "Tinel's",
    "tirosin": "Tirosint",
    "tavazanib": "Tivozanib",
    "topax": "Topamax",
    "terizomide": "Torsemide",
    "trudeo": "Toujeo",
    "trajenta": "Tradjenta",
    "trilogy": "Trelegy",
    "triantin": "Trientine",
    "trovaldi": "Trodelvy",
    "truvax": "Trulicity",
    "tula": "Trulicity",
    "triptase": "Tryptase",
    "avril b": "Ubrelvy",
    "relvi": "Ubrelvy",
    "urelvi": "Ubrelvy",
    "ybrelby": "Ubrelvy",
    "ubrevi": "Ubrelvy",
    "unisin": "Unasyn",
    "vyvaizmo": "Vabysmo",
    "byzmo": "Vabysmo",
    "belcyclovir": "Valcyclovir",
    "devantin": "Vantin",
    "veoza": "Veozah",
    "varus": "Veress",
    "vicaprofi": "Vicoprofen",
    "invistaril": "Vistaril",
    "vytopulse": "Vito Pulse",
    "fitrans": "Vitron-C",
    "viabelt": "Vivelle dot",
    "vyvildat": "Vivelle-Dot",
    "vyvaldot": "Vivelle-Dot",
    "raylar": "Vraylar",
    "waldier's ring": "Waldeyer's ring",
    "vigovi": "Wegovy",
    "wachovia": "Wegovy",
    "wacovi": "Wegovy",
    "wegovi": "Wegovy",
    "wigovi": "Wegovy",
    "wagovi": "Wegovy",
    "wogovi": "Wegovy",
    "begovi": "Wegovy",
    "wargavvy": "Wegovy",
    "wakobi": "Wegovy",
    "varubi": "Wegovy",
    "wegoweek": "Wegovy",
    "lidovi": "Wegovy",
    "wexella": "Wixela",
    "xham": "Xance",
    "karelto": "Xarelto",
    "zodians": "Xeljanz",
    "zygiva": "Xgeva",
    "zyaflex": "Xiaflex",
    "zybrom": "Xibrom",
    "zydra": "Xiidra",
    "x ray": "X-ray",
    "xtamsa": "Xtampza",
    "uvafem": "Yuvafem",
    "xatador": "Zaditor",
    "xanaflex": "Zanaflex",
    "zab spray": "Zavzpret",
    "zetbound": "Zepbound",
    "zap bound": "Zepbound",
    "zepban": "Zepbound",
    "zepion": "Zepbound",
    "zephond": "Zepbound",
    "zepfound": "Zepbound",
    "zebound": "Zepbound",
    "zepfam": "Zepbound",
    "zepaband": "Zepbound",
    "zep pound": "Zepbound",
    "zesteretic": "Zestoretic",
    "xeopatch": "Zio patch",
    "saphri": "Zofran",
    "zomix": "Zomax",
    "zonagrin": "Zonegran",
    "zin pouches": "Zyn pouches",
    "zantiga": "Zytiga",
    "acculair": "acular",
    "estrodol": "anastrozole",
    "pixaban": "apixaban",
    "exitinib": "axitinib",
    "azelastin": "azelastine",
    "bezoprolol": "bisoprolol",
    "carbadolol": "carvedilol",
    "carbadol": "carvedilol",
    "sefdenil": "cefdinir",
    "ceftinir": "cefdinir",
    "ceftin": "cefdinir",
    "cefalexin": "cephalexin",
    "sertizine": "cetirizine",
    "citrazine": "cetirizine",
    "chf": "CHF",
    "chlorothalidone": "chlorthalidone",
    "clotalodone": "chlorthalidone",
    "chondrocalcinoma": "chondrocalcinosis",
    "coronal neovascular membrane": "choroidal neovascular membrane",
    "clovoxam": "clobazam",
    "conjunctival itching": "conjunctival icterus",
    "cpd": "COPD",
    "copd": "COPD",
    "c p d": "COPD",
    "corticompressions": "core compressions",
    "ct scan": "CT scan",
    "ciproheptadine": "cyproheptadine",
    "proheptadine": "cyproheptadine",
    "durinavir": "darunavir",
    "teflokinic": "diclofenac",
    "dicyclamine": "dicyclomine",
    "tiltiazem": "diltiazem",
    "denepazole": "donepezil",
    "lexatine": "duloxetine",
    "ekg": "EKG",
    "elotriptan": "eletriptan",
    "amg": "EMG",
    "impagliflozin": "empagliflozin",
    "ampigliflozin": "empagliflozin",
    "endocantus": "empty can test",
    "endolytherin": "endolaser",
    "endo tracheal": "endotracheal",
    "interocutaneous fistula": "enterocutaneous fistula",
    "centophils": "eosinophils",
    "plarenone": "eplerenone",
    "s-cytografram": "escitalopram",
    "exomestane": "exemestane",
    "zetamibe": "ezetimibe",
    "fomotidine": "famotidine",
    "fibroosteus": "fibroosseous",
    "fenestribane": "finasteride",
    "fluconide": "flecainide",
    "phosphomycin": "fosfomycin",
    "glycanate": "glycinate",
    "guanfacin": "guanfacine",
    "hydrolyzine": "hydralazine",
    "hydraxazine": "hydroxyzine",
    "hyosiamine": "hyoscyamine",
    "iliorectal": "ileorectal",
    "erbazartan": "irbesartan",
    "irbisartan": "irbesartan",
    "herbisartan": "irbesartan",
    "erbisartan": "irbesartan",
    "j a m s i d i throw cars": "Jamshidi trocars",
    "jamsidi throw cars": "Jamshidi trocars",
    "k wires": "K-wires",
    "flunomide": "leflunomide",
    "luprolide": "leuprolide",
    "levothyroxetam": "levetiracetam",
    "levotirostim": "levetiracetam",
    "libotiroxine": "levothyroxine",
    "lysinopril": "lisinopril",
    "losonopril": "lisinopril",
    "lupus biliostomy": "loop ileostomy",
    "lisartan": "losartan",
    "lozartan": "losartan",
    "lasartan": "losartan",
    "lezartan": "losartan",
    "avad": "LVAD",
    "loxicant": "meloxicam",
    "velocican": "meloxicam",
    "mirapenem": "meropenem",
    "metocardamol": "methocarbamol",
    "metadrine": "midodrine",
    "metazapine": "mirtazapine",
    "ometazone": "mometasone",
    "mri": "MRI",
    "afloxacin": "ofloxacin",
    "afoxazine": "ofloxacin",
    "lomasartan": "olmesartan",
    "omasartan": "olmesartan",
    "omastatin": "olmesartan",
    "omosartan": "olmesartan",
    "optlume": "optilume",
    "obtilume": "optilume",
    "obdilume": "optilume",
    "pentoprazole": "pantoprazole",
    "per median": "paramedian",
    "paratropicular": "paratrabecular",
    "pegfograstim": "pegfilgrastim",
    "paraphobial": "perifoveal",
    "pets can": "PET scan",
    "pet scan": "PET scan",
    "pituitary rangers": "pituitary rongeurs",
    "posterior capsular pacification": "posterior capsular opacification",
    "post lateral gutters": "posterior lateral gutters",
    "pseudophagia": "pseudophakia",
    "retro peritoneal": "retroperitoneal",
    "butonavir": "ritonavir",
    "rizotriptan": "rizatriptan",
    "risotriptan": "rizatriptan",
    "ropinirol": "ropinirole",
    "rofenol": "ropinirole",
    "risuvastatin": "rosuvastatin",
    "vasuvastatin": "rosuvastatin",
    "rubastatin": "rosuvastatin",
    "semiglutide": "semaglutide",
    "septumaritoplasty": "septorhinoplasty",
    "sidenafil": "sildenafil",
    "simplicitin": "simvastatin",
    "sonohistogram": "sonohysterogram",
    "serafinib": "sorafenib",
    "sulcofate": "sucralfate",
    "synovicon dermatosis": "synovial chondromatosis",
    "tekral ms": "tacrolimus",
    "turbinafine": "terbinafine",
    "thalomotomy": "thalamotomy",
    "trizeptide": "tirzepatide",
    "trazepatide": "tirzepatide",
    "tarazepatide": "tirzepatide",
    "terpezotide": "tirzepatide",
    "trizepatide": "tirzepatide",
    "tapiramate": "topiramate",
    "tarsemide": "torsemide",
    "terastuzumab": "trastuzumab",
    "tresidone": "trazodone",
    "tramterene": "triamterene",
    "erythroplasty": "urethroplasty",
    "urethraleal": "urothelial",
    "alproate": "valproate",
    "varincline": "varenicline",
    "vilafaxine": "venlafaxine",
    "valazodone": "vilazodone",
    "vsco supplementation": "viscosupplementation",
    "zanabrutinib": "zanubrutinib",
    "sonisamide": "zonisamide",
    "zenosamide": "zonisamide",
};

exports.CLINICIAN_MEDICATION_MISTAKE_DICT = CLINICIAN_MEDICATION_MISTAKE_DICT;